FROM maven:3.9.9-openjdk-21 AS build
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk:21
EXPOSE 8080
ADD target/project-kafkaplaneapi.jar project-kafkaplaneapi.jar
ENTRYPOINT ["java","-jar","/project-kafkaplaneapi.jar"]